# Generated by Django 3.1.7 on 2021-04-21 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
